services:
  postgres:
    image: postgres:15-alpine
    container_name: cep-audit-postgres
    environment:
      POSTGRES_DB: cepauditdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mockoon:
    image: mockoon/cli:latest
    container_name: cep-audit-mockoon
    ports:
      - "8081:3000"
    volumes:
      - ./mockoon-cep.json:/data/mockoon-cep.json:ro
    command: ["-d", "/data/mockoon-cep.json", "-p", "3000", "-l", "0.0.0.0"]

volumes:
  postgres_data:
